Update ToolChain Version
cnblogs/cli pull request #6
Opened 2024-01-04 09:52 UTC by RocsSun

1. Update the ToolChain version to 2024-01-01, update GitHub CI to use the version and environment defined in Toolchain.toml
2. Change the crate to the database crate, and move the executable file to the bin directory

2024-01-07 22:39 UTC, cnblogs-dudu commented
建议使用 conventional commits，参考：
* [A specification for adding human and machine readable meaning to commit messages](https://www.conventionalcommits.org/)
* [Angular Commit Format Reference Sheet](https://gist.github.com/brianclements/841ea7bffdb01346392c)

2024-01-07 22:41 UTC, cnblogs-dudu requested changes
Use conventional commits

2024-01-24 15:34 UTC, RocsSun commented
# refactor:ing

Refactoring the ing subcommand while retaining the list and post subcommands. Add the following:

1. Use query instead of list and implement filtering using filtering conditions.
2. Use create instead of post to add private, tag, lucky, and other options.
3. Add delete to delete your specified ing.

## 中文(Chinese)

重构ing子命令，保留list和post子命令，未来可删除。新增如下：

1. 使用query代替list，并使用过滤条件实现过滤。
2. 使用create代替post，增加私有，标签，幸运等选项
3. 新增delete删除自己的指定闪存

2024-01-25 01:51 UTC, RocsSun commented
fix:ing
Fix ing create public content

2026-01-12 06:01 UTC, closed without merging